
'''
Define imaging parameters for each line.
'''

imaging_linedict = \
    {'12CO21': {"native": {'cellsize': '1arcsec', 'imsize': [512, 512],
                           'width': 1, 'start': 1, 'nchan': -1},
                "0p7kms": {'cellsize': '1arcsec', 'imsize': [512, 512],
                           'width': "0.67km/s", 'start': "-280km/s",
                           'nchan': 300},
                "1p3kms": {'cellsize': '1arcsec', 'imsize': [512, 512],
                           'width': "1.34km/s", 'start': "-280km/s",
                           'nchan': 150},
                "2kms": {'cellsize': '1arcsec', 'imsize': [512, 512],
                         'width': "2.0km/s", 'start': "-280km/s",
                         'nchan': 100},
                "2p6kms": {'cellsize': '1arcsec', 'imsize': [512, 512],
                           'width': "2.6km/s", 'start': "-280km/s",
                           'nchan': 77}},
     '13CO21': {"native": {'cellsize': '1arcsec', 'imsize': [512, 512],
                           'width': 1, 'start': 1, 'nchan': -1},
                "0p7kms": {'cellsize': '1arcsec', 'imsize': [512, 512],
                           'width': "0.67km/s", 'start': "-280km/s",
                           'nchan': 300},
                "1p3kms": {'cellsize': '1arcsec', 'imsize': [512, 512],
                           'width': "1.34km/s", 'start': "-280km/s",
                           'nchan': 150},
                "2kms": {'cellsize': '1arcsec', 'imsize': [512, 512],
                         'width': "2.0km/s", 'start': "-280km/s",
                         'nchan': 100},
                "2p6kms": {'cellsize': '1arcsec', 'imsize': [512, 512],
                           'width': "2.6km/s", 'start': "-280km/s",
                           'nchan': 77}},
     'C18O21': {"native": {'cellsize': '1arcsec', 'imsize': [512, 512],
                           'width': 1, 'start': 1, 'nchan': -1},
                "0p7kms": {'cellsize': '1arcsec', 'imsize': [512, 512],
                           'width': "0.67km/s", 'start': "-280km/s",
                           'nchan': 300},
                "1p3kms": {'cellsize': '1arcsec', 'imsize': [512, 512],
                           'width': "1.34km/s", 'start': "-280km/s",
                           'nchan': 150},
                "2kms": {'cellsize': '1arcsec', 'imsize': [512, 512],
                         'width': "2.0km/s", 'start': "-280km/s",
                         'nchan': 100},
                "2p6kms": {'cellsize': '1arcsec', 'imsize': [512, 512],
                           'width': "2.6km/s", 'start': "-280km/s",
                           'nchan': 77}},
     'H2CO_303_202': {"native": {'cellsize': '1arcsec', 'imsize': [512, 512],
                                 'width': 1, 'start': 1, 'nchan': -1},
                      "0p7kms": {'cellsize': '1arcsec', 'imsize': [512, 512],
                                 'width': "0.67km/s", 'start': "-280km/s",
                                 'nchan': 300},
                      "1p3kms": {'cellsize': '1arcsec', 'imsize': [512, 512],
                                 'width': "1.34km/s", 'start': "-280km/s",
                                 'nchan': 150},
                      "2kms": {'cellsize': '1arcsec', 'imsize': [512, 512],
                               'width': "2.0km/s", 'start': "-280km/s",
                               'nchan': 100},
                      "2p6kms": {'cellsize': '1arcsec', 'imsize': [512, 512],
                                 'width': "2.6km/s", 'start': "-280km/s",
                                 'nchan': 77}},
     'H2CO_322_221': {"native": {'cellsize': '1arcsec', 'imsize': [512, 512],
                                 'width': 1, 'start': 1, 'nchan': -1},
                      "0p7kms": {'cellsize': '1arcsec', 'imsize': [512, 512],
                                 'width': "0.67km/s", 'start': "-280km/s",
                                 'nchan': 300},
                      "1p3kms": {'cellsize': '1arcsec', 'imsize': [512, 512],
                                 'width': "1.34km/s", 'start': "-280km/s",
                                 'nchan': 150},
                      "2kms": {'cellsize': '1arcsec', 'imsize': [512, 512],
                               'width': "2.0km/s", 'start': "-280km/s",
                               'nchan': 100},
                      "2p6kms": {'cellsize': '1arcsec', 'imsize': [512, 512],
                                 'width': "2.6km/s", 'start': "-280km/s",
                                 'nchan': 77}},
     'H2CO_321_220': {"native": {'cellsize': '1arcsec', 'imsize': [512, 512],
                                 'width': 1, 'start': 1, 'nchan': -1},
                      "0p7kms": {'cellsize': '1arcsec', 'imsize': [512, 512],
                                 'width': "0.67km/s", 'start': "-280km/s",
                                 'nchan': 300},
                      "1p3kms": {'cellsize': '1arcsec', 'imsize': [512, 512],
                                 'width': "1.34km/s", 'start': "-280km/s",
                                 'nchan': 150},
                      "2kms": {'cellsize': '1arcsec', 'imsize': [512, 512],
                               'width': "2.0km/s", 'start': "-280km/s",
                               'nchan': 100},
                      "2p6kms": {'cellsize': '1arcsec', 'imsize': [512, 512],
                                 'width': "2.6km/s", 'start': "-280km/s",
                                 'nchan': 77}},
     }
